// Atlas figures for stages 1 and 2: the plane itself, and straight lines.
//
// One entry per concept, keyed by the exact term in the spine. Each is a spec
// for scripts/atlas-figures.mjs, so the picture is computed from these numbers
// and nothing is positioned by hand.
//
// `alt` is the accessible name. It is written per entry rather than generated,
// because a glossary figure has one job and the sentence that describes it is
// the same sentence a sighted reader would say out loud.

const P = { grid: 'lines', ticks: true };

export const ATLAS = {
  /* ---------------------------------------------------- 1. the plane itself */
  'point': { ...P, pts: [[2, 2]], alt: 'A single dot marked on a grid.' },
  'position': { ...P, pts: [[3, 1]], guides: [[3, 1]], alt: 'A dot with dashed lines dropped to each axis, fixing where it is.' },
  'location': { ...P, pts: [[3, 1, '(3, 1)']], guides: [[3, 1]], alt: 'A dot labelled with the pair 3, 1 that names it.' },
  'number line': { line: true, marks: [{ x: 2 }], alt: 'A number line from minus five to five with 2 marked.' },
  'one dimension': { line: true, marks: [{ x: -3 }, { x: 1 }], note: 'one number is enough', alt: 'A number line with two positions marked; one number fixes each.' },
  'two dimensions': { ...P, pts: [[3, 2]], guides: [[3, 2]], note: 'two numbers needed', alt: 'A dot needing both a horizontal and a vertical measurement to place it.' },
  'origin': { ...P, pts: [[0, 0, '(0, 0)']], alt: 'The point where the two axes cross, marked and labelled zero, zero.' },
  'axis': { ...P, axisHi: 'x', alt: 'One of the two reference lines, drawn heavier than the grid.' },
  'x-axis': { ...P, axisHi: 'x', text: [[3.4, -0.9, 'x', '#a25d2a', 11]], alt: 'The horizontal reference line, emphasised and labelled x.' },
  'y-axis': { ...P, axisHi: 'y', text: [[0.9, 3.6, 'y', '#a25d2a', 11]], alt: 'The vertical reference line, emphasised and labelled y.' },
  'axes': { ...P, axisHi: 'both', alt: 'Both reference lines emphasised, crossing at right angles.' },
  'coordinate plane': { ...P, alt: 'The full grid with both axes, on which any point can be placed.' },
  'Cartesian plane': { ...P, text: [[2.6, 2.6, 'I'], [-2.6, 2.6, 'II'], [-2.6, -2.6, 'III'], [2.6, -2.6, 'IV']], alt: 'The grid with its four quadrants numbered one to four, anticlockwise from the top right.' },
  'ordered pair': { ...P, pts: [[3, 1, '(3, 1)']], guides: [[3, 1]], note: 'input first', alt: 'A point labelled with its two numbers written in brackets, input first.' },
  'coordinate': { ...P, pts: [[3, 1]], segs: [[0, 0, 3, 0, '#e0813a', false, 3]], text: [[1.5, -0.9, '3']], alt: 'One of the two numbers, shown as the distance measured along an axis.' },
  'x-coordinate': { ...P, pts: [[3, 1]], segs: [[0, 0, 3, 0, '#e0813a', false, 3], [3, 0, 3, 1, '#5d6b7d', true, 1.2]], text: [[1.5, -0.9, '3', '#a25d2a']], alt: 'The horizontal measurement of a point, marked along the x-axis as 3.' },
  'y-coordinate': { ...P, pts: [[3, 1]], segs: [[0, 0, 0, 1, '#12897c', false, 3], [0, 1, 3, 1, '#5d6b7d', true, 1.2]], text: [[-0.7, 0.8, '1', '#10796e']], alt: 'The vertical measurement of a point, marked up the y-axis as 1.' },
  'abscissa': { ...P, pts: [[3, 1]], segs: [[0, 0, 3, 0, '#e0813a', false, 3]], note: 'the x-coordinate', alt: 'The older name for the x-coordinate, shown as a length along the horizontal axis.' },
  'ordinate': { ...P, pts: [[3, 1]], segs: [[0, 0, 0, 1, '#12897c', false, 3]], note: 'the y-coordinate', alt: 'The older name for the y-coordinate, shown as a length up the vertical axis.' },
  'plotting a point': { ...P, arrows: [[0, 0, 3, 0, '#e0813a'], [3, 0, 3, 2, '#12897c']], pts: [[3, 2]], note: 'across, then up', alt: 'Two arrows: first across three, then up two, arriving at the point.' },
  'reading a point': { ...P, pts: [[3, 2]], arrows: [[3, 2, 3, 0, '#e0813a'], [3, 2, 0, 2, '#12897c']], note: 'point to axes', alt: 'Arrows leaving a point toward each axis, to read off its two numbers.' },
  'quadrant': { ...P, quads: [1], alt: 'One of the four regions the axes cut the plane into, shaded.' },
  'first quadrant': { ...P, quads: [1], pts: [[2.5, 2.5, '(+, +)']], alt: 'The top right region, where both coordinates are positive.' },
  'second quadrant': { ...P, quads: [2], pts: [[-2.5, 2.5, '(−, +)']], alt: 'The top left region, where x is negative and y is positive.' },
  'third quadrant': { ...P, quads: [3], pts: [[-2.5, -2.5, '(−, −)']], alt: 'The bottom left region, where both coordinates are negative.' },
  'fourth quadrant': { ...P, quads: [4], pts: [[2.5, -2.5, '(+, −)']], alt: 'The bottom right region, where x is positive and y is negative.' },
  'sign of a coordinate': { ...P, pts: [[2.6, 2.6, '', '#12897c'], [-2.6, 2.6, '', '#e0813a'], [-2.6, -2.6, '', '#c0504d'], [2.6, -2.6, '', '#5d6b7d']], text: [[2.6, 1.6, '+ +'], [-2.6, 1.6, '− +'], [-2.6, -3.6, '− −'], [2.6, -3.6, '+ −']], alt: 'A point in each quadrant, labelled with the signs its two coordinates carry.' },
  'positive direction': { ...P, arrows: [[0, 0, 4, 0, '#12897c'], [0, 0, 0, 4, '#12897c']], alt: 'Arrows running right and upward, the directions counted as positive.' },
  'negative direction': { ...P, arrows: [[0, 0, -4, 0, '#c0504d'], [0, 0, 0, -4, '#c0504d']], alt: 'Arrows running left and downward, the directions counted as negative.' },
  'gridline': { ...P, hiGrid: 2, alt: 'One line of the grid emphasised: every point on it shares an x-coordinate.' },
  'lattice point': { ...P, grid: 'dots', pts: [[2, 3], [-3, 1], [0, -2]], alt: 'A grid of dots at whole-number positions, with three of them marked.' },
  'tick mark': { ...P, hiTick: 3, alt: 'The small strokes counting units along an axis, with the third emphasised.' },
  'scale': { ...P, x0: -50, x1: 50, y0: -50, y1: 50, grid: 'none', ticks: false, segs: [[0, 0, 40, 0, '#e0813a', false, 3]], text: [[20, -9, '40 units']], alt: 'The same axes covering a much larger range, showing that the choice of units is free.' },
  'unit': { ...P, bands: [[0, 0, 1, 1]], text: [[0.5, 1.5, '1 by 1']], alt: 'A single square of the grid shaded, one unit across and one unit up.' },
  'equal scaling': { ...P, bands: [[1, 1, 3, 3]], note: 'a square looks square', alt: 'A two by two region drawn on axes with matching units, so it appears square.' },
  'distorted scaling': { ...P, y0: -12, y1: 12, bands: [[1, 1, 3, 3]], note: 'the same square, squashed', alt: 'The same two by two region on axes with different units, so it appears as a flat rectangle.' },
  'axis label': { ...P, axisHi: 'both', text: [[4.2, -0.9, 'x', '#a25d2a', 11], [0.9, 4.2, 'y', '#a25d2a', 11]], alt: 'The two axes named, so a reader knows which quantity runs which way.' },
  'the point (0, 0)': { ...P, pts: [[0, 0, '(0, 0)']], alt: 'The origin, whose two coordinates are both zero.' },
  'distance from an axis': { ...P, pts: [[3, 2]], segs: [[3, 2, 3, 0, '#e0813a', false, 2.6], [3, 2, 0, 2, '#12897c', false, 2.6]], right: [3, 0, -1, 1], alt: 'Two perpendicular segments from a point to each axis, each measuring one coordinate.' },
  'above and below': { ...P, shade: { above: 0, below: 0 }, alt: 'The plane split by the horizontal axis: positive outputs above, negative below.' },
  'left and right': { ...P, shade: { left: 0, right: 0 }, alt: 'The plane split by the vertical axis: positive inputs to the right, negative to the left.' },
  'reference frame': { ...P, pts: [[0, 0, 'origin'], [3, 2, 'measured from it']], arrows: [[0, 0, 3, 2, '#e0813a']], alt: 'A point measured from a chosen origin, which is what makes its two numbers mean anything.' },
  'convention (input first)': { ...P, pts: [[3, 1, '(3, 1)']], guides: [[3, 1]], note: 'across, then up', alt: 'The agreed order: the first number is measured across, the second up.' },
  'the pair (3, 1) against (1, 3)': { ...P, pts: [[3, 1, '(3, 1)', '#12897c'], [1, 3, '(1, 3)', '#e0813a']], alt: 'Two different points, showing that swapping the two numbers moves the point.' },

  /* --------------------------------------------- 2. straight lines and segments */
  'straight line': { ...P, lines: [{ m: 0.7, c: 0.5 }], alt: 'A line running the full width of the frame, continuing beyond it both ways.' },
  'line segment': { ...P, segs: [[-2, -1, 3, 2]], pts: [[-2, -1], [3, 2]], alt: 'A piece of a line with a marked point at each end.' },
  'ray': { ...P, rays: [[-2, -1, 3, 2]], pts: [[-2, -1]], alt: 'A line with one endpoint, running on without end in the other direction.' },
  'endpoint': { ...P, segs: [[-2, -1, 3, 2]], pts: [[-2, -1, 'end'], [3, 2, 'end']], alt: 'The two points at which a segment stops.' },
  'interior point': { ...P, segs: [[-2, -1, 3, 2]], pts: [[-2, -1, '', '#5d6b7d'], [3, 2, '', '#5d6b7d'], [0.5, 0.5, 'between', '#e0813a']], alt: 'A point lying on a segment, strictly between its two ends.' },
  'betweenness': { ...P, segs: [[-3, 0, 3, 0]], pts: [[-3, 0, 'A'], [0, 0, 'B'], [3, 0, 'C']], note: 'B lies between A and C', alt: 'Three points in a row, the middle one lying between the other two.' },
  'length of a segment': { ...P, segs: [[-1, -1, 3, 2]], pts: [[-1, -1], [3, 2]], tri: [-1, -1, 3, 2], note: 'length 5', alt: 'A segment with its horizontal and vertical legs drawn, giving a right triangle whose hypotenuse is the length.' },
  'distance formula': { ...P, tri: [-1, -1, 3, 2], pts: [[-1, -1], [3, 2]], text: [[1, -1.9, '4'], [3.7, 0.5, '3']], note: '√(16+9) = 5', alt: 'The distance between two points found from the legs 4 and 3 by Pythagoras, giving 5.' },
  'Pythagoras in the plane': { ...P, tri: [0, 0, 4, 3], pts: [[0, 0], [4, 3]], right: [4, 0, -1, 1], note: '3² + 4² = 5²', alt: 'A right triangle on the grid with legs 3 and 4 and hypotenuse 5.' },
  'midpoint': { ...P, segs: [[-3, -2, 3, 2]], pts: [[-3, -2], [3, 2], [0, 0, 'midpoint', '#e0813a']], alt: 'The point exactly halfway along a segment.' },
  'midpoint formula': { ...P, segs: [[-3, -2, 3, 2]], pts: [[-3, -2, '(−3, −2)'], [3, 2, '(3, 2)'], [0, 0, '(0, 0)', '#e0813a']], note: 'average each coordinate', alt: 'A midpoint whose coordinates are the averages of the two endpoints.' },
  'section formula': { ...P, segs: [[-4, -2, 4, 2]], pts: [[-4, -2], [4, 2], [0, 0, '1 : 1', '#e0813a'], [2, 1, '3 : 1', '#12897c']], alt: 'Two points dividing a segment in stated ratios.' },
  'internal division': { ...P, segs: [[-3, 0, 3, 0]], pts: [[-3, 0, 'A'], [3, 0, 'B'], [1, 0, 'P', '#e0813a']], note: 'P is inside AB', alt: 'A dividing point lying inside the segment.' },
  'external division': { ...P, segs: [[-3, 0, 3, 0]], pts: [[-3, 0, 'A'], [3, 0, 'B'], [4.4, 0, 'P', '#c0504d']], note: 'P is outside AB', alt: 'A dividing point lying beyond one end of the segment.' },
  'ratio along a segment': { ...P, segs: [[-4, -2, 4, 2]], pts: [[-4, -2], [4, 2], [0, 0, '', '#e0813a']], text: [[-2, -1.9, '1'], [2, 0.1, '1']], alt: 'A segment split into two parts whose lengths are compared.' },
  'collinear points': { ...P, lines: [{ m: 0.5, c: 0 }], pts: [[-4, -2], [0, 0], [3, 1.5]], alt: 'Three points that all lie on one straight line.' },
  'horizontal line': { ...P, lines: [{ y: 2 }], note: 'y = 2', alt: 'A flat line at height two, every point on it sharing the same y.' },
  'vertical line': { ...P, lines: [{ x: 2 }], note: 'x = 2', alt: 'An upright line at position two, every point on it sharing the same x.' },
  'oblique line': { ...P, lines: [{ m: 0.8, c: -0.5 }], note: 'neither flat nor upright', alt: 'A slanted line, neither horizontal nor vertical.' },
  'slope': { ...P, lines: [{ m: 0.75, c: 0 }], tri: [0, 0, 4, 3], note: '3 up per 4 across', alt: 'A line with its rise and run drawn as the two legs of a triangle.' },
  'gradient': { ...P, lines: [{ m: 0.75, c: 0 }], tri: [0, 0, 4, 3], note: 'the same number as slope', alt: 'The same quantity as slope, under its other name.' },
  'rise': { ...P, lines: [{ m: 0.75, c: 0 }], segs: [[4, 0, 4, 3, '#12897c', false, 3]], text: [[4.6, 1.5, 'rise', '#10796e']], alt: 'The vertical leg of the slope triangle, measured upward.' },
  'run': { ...P, lines: [{ m: 0.75, c: 0 }], segs: [[0, 0, 4, 0, '#e0813a', false, 3]], text: [[2, -0.9, 'run', '#a25d2a']], alt: 'The horizontal leg of the slope triangle, measured across.' },
  'rise over run': { ...P, lines: [{ m: 0.75, c: 0 }], tri: [0, 0, 4, 3], note: '3 ÷ 4 = 0.75', alt: 'The rise divided by the run, which is the slope.' },
  'steepness': { ...P, lines: [{ m: 0.4, c: 0, c2: '#5d6b7d' }, { m: 2, c: 0 }], note: 'steeper means bigger', alt: 'Two lines through the origin, the steeper one having the larger slope.' },
  'positive slope': { ...P, lines: [{ m: 0.9, c: 0 }], note: 'rises left to right', alt: 'A line climbing from left to right.' },
  'negative slope': { ...P, lines: [{ m: -0.9, c: 0 }], note: 'falls left to right', alt: 'A line dropping from left to right.' },
  'zero slope': { ...P, lines: [{ y: 1.5 }], note: 'no rise at all', alt: 'A flat line, whose rise is zero however far you run.' },
  'undefined slope': { ...P, lines: [{ x: 1.5 }], note: 'no run to divide by', alt: 'An upright line, whose run is zero, so the division cannot be done.' },
  'angle of inclination': { ...P, lines: [{ m: 1, c: 0 }], segs: [[0, 0, 3.4, 0, '#e0813a', false, 2]], text: [[1.6, 0.55, '45°', '#a25d2a']], alt: 'The angle a line makes with the horizontal axis.' },
  'parallel lines': { ...P, lines: [{ m: 0.8, c: 2 }, { m: 0.8, c: -2 }], note: 'same slope', alt: 'Two lines with the same slope, never meeting.' },
  'perpendicular lines': { ...P, lines: [{ m: 1, c: 0 }, { m: -1, c: 0, c2: '#e0813a' }], right: [0, 0, 1, 1], note: 'slopes 1 and −1', alt: 'Two lines crossing at right angles, their slopes multiplying to minus one.' },
  'negative reciprocal': { ...P, lines: [{ m: 2, c: 0 }, { m: -0.5, c: 0, c2: '#e0813a' }], note: '2 and −1/2', alt: 'A pair of perpendicular slopes: one is minus one divided by the other.' },
  'x-intercept': { ...P, lines: [{ m: 0.8, c: -1.6 }], pts: [[2, 0, '(2, 0)', '#e0813a']], alt: 'Where a line crosses the horizontal axis, so its output is zero.' },
  'y-intercept': { ...P, lines: [{ m: 0.8, c: -1.6 }], pts: [[0, -1.6, '(0, −1.6)', '#12897c']], alt: 'Where a line crosses the vertical axis, so its input is zero.' },
  'equation of a line': { ...P, lines: [{ m: 0.5, c: 1 }], pts: [[2, 2], [-2, 0]], note: 'y = 0.5x + 1', alt: 'A line together with the equation every point on it satisfies.' },
  'linear equation': { ...P, lines: [{ m: -0.6, c: 2 }], note: 'first power only', alt: 'An equation whose graph is a straight line.' },
  'slope-intercept form': { ...P, lines: [{ m: 0.75, c: 1.5 }], pts: [[0, 1.5, '', '#12897c']], tri: [0, 1.5, 4, 4.5], note: 'y = mx + c', alt: 'A line with its y-intercept marked and its slope drawn, the two numbers the form names.' },
  'point-slope form': { ...P, lines: [{ m: 0.75, c: -0.25 }], pts: [[1, 0.5, '(1, 0.5)', '#e0813a']], tri: [1, 0.5, 4, 2.75], note: 'through one point, at one slope', alt: 'A line fixed by one point it passes through and its slope.' },
  'two-point form': { ...P, lines: [{ m: 0.75, c: -0.25 }], pts: [[-3, -2.5], [3, 2]], note: 'two points fix a line', alt: 'A line determined by two of its points.' },
  'standard form': { ...P, lines: [{ m: -0.75, c: 3 }], pts: [[4, 0], [0, 3]], note: '3x + 4y = 12', alt: 'A line written with both variables on one side, with both intercepts marked.' },
  'general form': { ...P, lines: [{ m: -0.75, c: 3 }], note: 'Ax + By + C = 0', alt: 'The same line with everything moved to one side and zero on the other.' },
  'intercept form': { ...P, lines: [{ m: -0.75, c: 3 }], segs: [[0, 0, 4, 0, '#e0813a', false, 3], [0, 0, 0, 3, '#12897c', false, 3]], pts: [[4, 0], [0, 3]], note: 'x/4 + y/3 = 1', alt: 'A line written from the two lengths it cuts off on the axes.' },
  'distance from a point to a line': { ...P, lines: [{ m: 0.5, c: -1 }], pts: [[-1, 3, 'P']], segs: [[-1, 3, 0.6, -0.7, '#e0813a', true, 2]], right: [0.6, -0.7, -0.7, 1], alt: 'The shortest segment from a point to a line, meeting it at a right angle.' },
  'foot of the perpendicular': { ...P, lines: [{ m: 0.5, c: -1 }], pts: [[-1, 3, 'P'], [0.6, -0.7, 'foot', '#e0813a']], segs: [[-1, 3, 0.6, -0.7, '#e0813a', true, 2]], alt: 'The point where the perpendicular from P meets the line.' },
  'angle between two lines': { ...P, lines: [{ m: 0.3, c: 0 }, { m: 1.6, c: 0, c2: '#e0813a' }], text: [[2.2, 0.9, 'θ', '#5d6b7d', 11]], alt: 'Two lines crossing, with the angle between them marked.' },
  'perpendicular bisector': { ...P, segs: [[-3, -1, 3, 1]], pts: [[-3, -1, 'A'], [3, 1, 'B'], [0, 0, '', '#e0813a']], lines: [{ m: -3, c: 0, c2: '#e0813a' }], right: [0, 0, 1, 3], alt: 'The line cutting a segment in half at a right angle.' },
  'locus of equidistant points': { ...P, pts: [[-3, 0, 'A'], [3, 0, 'B']], lines: [{ x: 0, c2: '#e0813a' }], segs: [[-3, 0, 0, 2.5, '#5d6b7d', true, 1.3], [3, 0, 0, 2.5, '#5d6b7d', true, 1.3]], alt: 'Every point on the marked line is the same distance from A as from B.' },
  'direction of travel': { ...P, arrows: [[-3, -2, 3, 2, '#12897c']], pts: [[-3, -2, 'from'], [3, 2, 'to']], alt: 'A segment with an arrow, so it now carries a direction as well as a length.' },
  'a line as a set of points': { ...P, lines: [{ m: 0.5, c: 0.5, c2: '#d8d3c7' }], pts: [[-4, -1.5], [-2, -0.5], [0, 0.5], [2, 1.5], [4, 2.5]], note: 'every point that fits the rule', alt: 'Points scattered along a faint line, each one satisfying the same equation.' }
};
