// Atlas figures for stages 3, 4 and 5: regions, the function idea, and the
// families of curves. Same contract as atlas-1-2.js — a spec per concept, and
// the picture computed from these numbers alone.

const P = { grid: 'lines', ticks: true };
const B = { grid: 'none', ticks: false, axes: false, arrowheads: false, x0: -5, x1: 5, y0: -4, y1: 4 };
const tri = (a, b, c, o = {}) => ({ pts: [a, b, c], ...o });
const sq = x => x * x;

export const ATLAS_3_5 = {
  /* ------------------------------------------- 3. regions, shapes, systems */
  'polygon': { ...P, polys: [{ pts: [[-3, -2], [1, -3], [3, 1], [0, 3], [-3, 1]] }], alt: 'A closed shape made of straight sides.' },
  'vertex': { ...P, polys: [{ pts: [[-3, -2], [2, -2], [0, 3]] }], pts: [[0, 3, 'vertex', '#e0813a']], alt: 'A corner of a polygon, where two sides meet.' },
  'side': { ...P, polys: [{ pts: [[-3, -2], [2, -2], [0, 3]], fill: 'none' }], segs: [[-3, -2, 2, -2, '#e0813a', false, 3.5]], alt: 'One straight edge of a polygon, emphasised.' },
  'triangle': { ...P, polys: [tri([-3, -2], [3, -2], [0, 3])], alt: 'Three points joined by three straight sides.' },
  'right triangle': { ...P, polys: [tri([-2, -2], [2, -2], [-2, 2])], right: [-2, -2, 1, 1], alt: 'A triangle with one square corner.' },
  'isosceles triangle': { ...P, polys: [tri([-2, -2], [2, -2], [0, 3])], text: [[-1.6, 0.6, '='], [1.6, 0.6, '=']], alt: 'A triangle with two sides of equal length.' },
  'equilateral triangle': { ...P, polys: [tri([-2, -1.7], [2, -1.7], [0, 1.76])], note: 'all three equal', alt: 'A triangle with all three sides equal.' },
  'quadrilateral': { ...P, polys: [{ pts: [[-3, -2], [3, -3], [2, 2], [-2, 3]] }], alt: 'A closed shape with four straight sides.' },
  'rectangle': { ...P, polys: [{ pts: [[-3, -2], [3, -2], [3, 2], [-3, 2]] }], right: [-3, -2, 1, 1], alt: 'Four sides, four right angles, opposite sides equal.' },
  'square': { ...P, polys: [{ pts: [[-2, -2], [2, -2], [2, 2], [-2, 2]] }], right: [-2, -2, 1, 1], alt: 'A rectangle whose four sides are all the same length.' },
  'parallelogram': { ...P, polys: [{ pts: [[-3, -2], [1, -2], [3, 2], [-1, 2]] }], alt: 'Four sides, with each pair of opposite sides parallel.' },
  'rhombus': { ...P, polys: [{ pts: [[0, -3], [3, 0], [0, 3], [-3, 0]] }], alt: 'A parallelogram with all four sides equal.' },
  'trapezium': { ...P, polys: [{ pts: [[-3, -2], [3, -2], [1.5, 2], [-1.5, 2]] }], alt: 'A quadrilateral with exactly one pair of parallel sides.' },
  'perimeter': { ...P, polys: [{ pts: [[-3, -2], [3, -2], [3, 2], [-3, 2]], fill: 'none', stroke: '#e0813a', wid: 3.5 }], note: 'the way round', alt: 'The total distance around the outside of a shape.' },
  'area of a triangle': { ...P, polys: [tri([-3, -2], [3, -2], [1, 2])], segs: [[1, 2, 1, -2, '#e0813a', true, 1.6]], note: 'half base times height', alt: 'A triangle with its base and perpendicular height marked.' },
  'shoelace formula': { ...P, polys: [tri([-3, -2], [3, -1], [0, 3], { fill: 'none' })], pts: [[-3, -2, '(−3,−2)'], [3, -1, '(3,−1)'], [0, 3, '(0,3)']], note: 'area from the corners', alt: 'A triangle labelled with its three vertex coordinates, from which the area can be computed directly.' },
  'determinant form': { ...P, polys: [tri([0, 0], [4, 1], [1, 3])], note: 'half |x1y2 − x2y1|', alt: 'A triangle with one vertex at the origin, whose area is half a determinant.' },
  'area of a polygon': { ...P, polys: [{ pts: [[-3, -2], [2, -3], [3, 1], [0, 3], [-3, 1]] }], segs: [[-3, -2, 3, 1, '#5d6b7d', true, 1.2], [-3, -2, 0, 3, '#5d6b7d', true, 1.2]], note: 'cut into triangles', alt: 'A five-sided shape split by dashed lines into triangles.' },
  'region': { ...P, bands: [[-3, -1, 2, 3]], alt: 'A part of the plane, shaded.' },
  'half-plane': { ...P, lines: [{ m: 0.5, c: 0 }], shade: { above: 0 }, alt: 'Everything on one side of a line.' },
  'inequality': { ...P, lines: [{ y: 1 }], shade: { above: 1 }, note: 'y ≥ 1', alt: 'A boundary with everything above it shaded.' },
  'linear inequality': { ...P, lines: [{ m: -1, c: 2 }], shade: { below: 0 }, note: 'x + y ≤ 2', alt: 'A straight boundary with the satisfying side shaded.' },
  'strict inequality': { ...P, lines: [{ y: 1, dash: true }], shade: { above: 1 }, note: 'y > 1, boundary excluded', alt: 'A dashed boundary, showing the line itself is not included.' },
  'boundary line': { ...P, lines: [{ m: -1, c: 2, c2: '#e0813a' }], shade: { below: 0 }, alt: 'The edge of a region, drawn solid because it belongs to it.' },
  'shaded region': { ...P, lines: [{ m: 1, c: -1 }, { m: -1, c: 3 }], polys: [{ pts: [[-5, -5], [2, 1], [-5, 5]], fill: '#cfe6e1', stroke: 'none' }], alt: 'The overlap of two conditions, shaded.' },
  'feasible region': { ...P, polys: [{ pts: [[0, 0], [3.5, 0], [3, 2], [1, 3], [0, 2.5]] }], lines: [{ m: -1, c: 4, dash: true, c2: '#5d6b7d' }], alt: 'The set of points satisfying every constraint at once.' },
  'convex region': { ...P, polys: [{ pts: [[-3, -2], [3, -2], [2, 2], [-2, 2]] }], segs: [[-3, -2, 2, 2, '#e0813a', true, 1.6]], note: 'the join stays inside', alt: 'A region where a segment between any two of its points stays inside it.' },
  'bounded region': { ...P, polys: [{ pts: [[-2, -2], [2, -2], [2, 2], [-2, 2]] }], note: 'fits in a box', alt: 'A region that can be enclosed entirely.' },
  'unbounded region': { ...P, lines: [{ m: 0.4, c: 1 }], shade: { above: 1 }, note: 'runs on forever', alt: 'A region that continues without limit in some direction.' },
  'intersection of two lines': { ...P, lines: [{ m: 1, c: -1 }, { m: -0.5, c: 2, c2: '#e0813a' }], pts: [[2, 1]], alt: 'Two lines crossing at a single point.' },
  'point of intersection': { ...P, lines: [{ m: 1, c: -1 }, { m: -0.5, c: 2, c2: '#e0813a' }], pts: [[2, 1, '(2, 1)']], guides: [[2, 1]], alt: 'The one point lying on both lines, with its coordinates read off.' },
  'simultaneous equations': { ...P, lines: [{ m: 1, c: -1 }, { m: -0.5, c: 2, c2: '#e0813a' }], pts: [[2, 1]], note: 'both true at once', alt: 'Two equations whose graphs meet where both are satisfied.' },
  'system of equations': { ...P, lines: [{ m: 1, c: -1 }, { m: -0.5, c: 2, c2: '#e0813a' }, { m: 3, c: -5, c2: '#c0504d' }], pts: [[2, 1]], alt: 'Several equations considered together, here all passing through one point.' },
  'unique solution': { ...P, lines: [{ m: 1, c: 0 }, { m: -1, c: 2, c2: '#e0813a' }], pts: [[1, 1]], note: 'exactly one crossing', alt: 'Two lines of different slopes, meeting exactly once.' },
  'no solution': { ...P, lines: [{ m: 0.8, c: 2 }, { m: 0.8, c: -2, c2: '#e0813a' }], note: 'parallel, never meet', alt: 'Two parallel lines, which never cross.' },
  'infinitely many solutions': { ...P, lines: [{ m: 0.8, c: 0, c2: '#e0813a' }, { m: 0.8, c: 0, dash: true }], note: 'the same line twice', alt: 'Two equations describing the same line, so every point on it solves both.' },
  'consistent system': { ...P, lines: [{ m: 1, c: 0 }, { m: -1, c: 2, c2: '#e0813a' }], pts: [[1, 1]], note: 'at least one solution', alt: 'A system with at least one common point.' },
  'inconsistent system': { ...P, lines: [{ m: 0.8, c: 2 }, { m: 0.8, c: -2, c2: '#e0813a' }], note: 'no common point', alt: 'A system whose lines never meet, so nothing satisfies all of it.' },
  'dependent equations': { ...P, lines: [{ m: -0.6, c: 1, c2: '#e0813a' }, { m: -0.6, c: 1, dash: true }], note: 'one is a multiple of the other', alt: 'Two equations that are the same line, one a multiple of the other.' },
  'graphical solution': { ...P, lines: [{ m: 1.5, c: -2 }, { m: -0.5, c: 2, c2: '#e0813a' }], pts: [[2, 1]], guides: [[2, 1]], note: 'read it off', alt: 'Solving by drawing both lines and reading the crossing point.' },
  'substitution method': { ...P, lines: [{ m: 1, c: -1 }, { x: 2, c2: '#e0813a' }], pts: [[2, 1]], note: 'fix one, find the other', alt: 'One variable pinned, reducing the problem to a single unknown.' },
  'elimination method': { ...P, lines: [{ m: 1, c: -1 }, { m: -0.5, c: 2, c2: '#e0813a' }, { y: 1, c2: '#5d6b7d', dash: true }], pts: [[2, 1]], note: 'combine to remove one', alt: 'Two equations combined so one variable disappears.' },
  'linear programming': { ...P, polys: [{ pts: [[0, 0], [3.5, 0], [3, 2], [1, 3], [0, 2.5]] }], pts: [[3, 2, 'best', '#e0813a']], lines: [{ m: -0.8, c: 4.4, dash: true, c2: '#5d6b7d' }], alt: 'A feasible region with the best corner marked for a given objective.' },
  'objective function': { ...P, polys: [{ pts: [[0, 0], [3.5, 0], [3, 2], [1, 3], [0, 2.5]] }], lines: [{ m: -0.8, c: 1.5, dash: true, c2: '#5d6b7d' }, { m: -0.8, c: 3, dash: true, c2: '#5d6b7d' }, { m: -0.8, c: 4.4, c2: '#e0813a' }], alt: 'Parallel lines of equal value sliding across a region until they leave it.' },
  'corner point': { ...P, polys: [{ pts: [[0, 0], [3.5, 0], [3, 2], [1, 3], [0, 2.5]] }], pts: [[0, 0], [3.5, 0], [3, 2], [1, 3], [0, 2.5]], alt: 'The vertices of a feasible region, where the best value must occur.' },
  'concurrency': { ...P, lines: [{ m: 1, c: -1 }, { m: -0.5, c: 2, c2: '#e0813a' }, { m: 3, c: -5, c2: '#c0504d' }], pts: [[2, 1]], note: 'three lines, one point', alt: 'Three or more lines all passing through the same point.' },
  'medians': { ...P, polys: [tri([-3, -2], [3, -2], [0, 3], { fill: 'none' })], segs: [[-3, -2, 1.5, 0.5, '#e0813a', false, 1.6], [3, -2, -1.5, 0.5, '#e0813a', false, 1.6], [0, 3, 0, -2, '#e0813a', false, 1.6]], pts: [[0, -0.33]], alt: 'The three lines from each vertex to the midpoint of the opposite side.' },
  'centroid': { ...P, polys: [tri([-3, -2], [3, -2], [0, 3], { fill: 'none' })], segs: [[-3, -2, 1.5, 0.5, '#d8d3c7', false, 1.4], [3, -2, -1.5, 0.5, '#d8d3c7', false, 1.4], [0, 3, 0, -2, '#d8d3c7', false, 1.4]], pts: [[0, -0.33, 'centroid', '#e0813a']], alt: 'Where the three medians meet, the average of the three vertices.' },
  'circumcentre': { ...P, polys: [tri([-3, -2], [3, -2], [0, 3], { fill: 'none' })], circles: [{ cx: 0, cy: -0.17, r: 3.005 }], pts: [[0, -0.17, '', '#e0813a']], alt: 'The centre of the circle passing through all three vertices.' },
  'incentre': { ...P, polys: [tri([-3, -2], [3, -2], [0, 3], { fill: 'none' })], circles: [{ cx: 0, cy: -0.55, r: 1.45, stroke: '#e0813a' }], pts: [[0, -0.55, '', '#e0813a']], alt: 'The centre of the largest circle that fits inside the triangle.' },
  'orthocentre': { ...P, polys: [tri([-3, -2], [3, -2], [0, 3], { fill: 'none' })], segs: [[0, 3, 0, -2, '#d8d3c7', false, 1.4], [-3, -2, 1.8, 1.2, '#d8d3c7', false, 1.4], [3, -2, -1.8, 1.2, '#d8d3c7', false, 1.4]], pts: [[0, 0.6, '', '#e0813a']], alt: 'Where the three altitudes meet.' },
  'Euler line': { ...P, polys: [tri([-3, -2], [3, -2], [0, 3], { fill: 'none' })], pts: [[0, -0.17], [0, -0.33], [0, 0.6]], lines: [{ x: 0, c2: '#e0813a', dash: true }], note: 'three centres, one line', alt: 'The circumcentre, centroid and orthocentre all lying on a single line.' },

  /* ------------------------------------------------- 4. the function idea */
  'relation': { ...B, pts: [[-2.5, 2, '', '#e0813a'], [-2.5, 0, '', '#e0813a'], [-2.5, -2, '', '#e0813a'], [2.5, 2], [2.5, -1]], arrows: [[-2.2, 2, 2.2, 2], [-2.2, 0, 2.2, -1], [-2.2, -2, 2.2, 2], [-2.2, -2, 2.2, -1]], alt: 'Any pairing between two sets, with no rule about how many arrows leave an input.' },
  'function': { ...B, pts: [[-2.5, 2, '', '#e0813a'], [-2.5, 0, '', '#e0813a'], [-2.5, -2, '', '#e0813a'], [2.5, 2], [2.5, 0], [2.5, -2]], arrows: [[-2.2, 2, 2.2, 2], [-2.2, 0, 2.2, 0], [-2.2, -2, 2.2, -2]], alt: 'A pairing where exactly one arrow leaves each input.' },
  'rule': { ...B, pts: [[-2.8, 0, '', '#e0813a'], [2.8, 0]], arrows: [[-2.4, 0, 2.4, 0]], text: [[0, 0.7, 'double it'], [-2.8, -1, 'in'], [2.8, -1, 'out']], alt: 'An instruction turning one thing into another.' },
  'input': { ...B, pts: [[-2.8, 0, '', '#e0813a'], [2.8, 0, '', '#d8d3c7']], arrows: [[-2.4, 0, 2.4, 0]], text: [[-2.8, -1, 'input', '#a25d2a']], alt: 'The thing handed to a rule.' },
  'output': { ...B, pts: [[-2.8, 0, '', '#d8d3c7'], [2.8, 0, '', '#12897c']], arrows: [[-2.4, 0, 2.4, 0]], text: [[2.8, -1, 'output', '#10796e']], alt: 'The thing a rule returns.' },
  'domain': { line: true, spans: [[-5, -2, 'out'], [-2, 5]], marks: [{ x: -2 }], note: 'the inputs allowed', alt: 'The stretch of the number line a rule will accept.' },
  'range': { line: true, spans: [[0, 5]], marks: [{ x: 0 }], note: 'the outputs produced', alt: 'The stretch of values a rule actually returns.' },
  'codomain': { ...B, pts: [[-2.5, 1.5, '', '#e0813a'], [-2.5, -1.5, '', '#e0813a'], [2.5, 2.5], [2.5, 0.5], [2.5, -1.5, '', '#d8d3c7'], [2.5, -3, '', '#d8d3c7']], arrows: [[-2.2, 1.5, 2.2, 2.5], [-2.2, -1.5, 2.2, 0.5]], note: 'the set outputs are drawn from', alt: 'The set the outputs come from, which may be larger than the range.' },
  'image': { ...B, pts: [[-2.5, 0, '3', '#e0813a'], [2.5, 0, '9']], arrows: [[-2.2, 0, 2.2, 0]], text: [[2.5, -1.2, 'the image of 3']], alt: 'What a particular input is sent to.' },
  'preimage': { ...B, pts: [[-2.5, 0, '3', '#12897c'], [2.5, 0, '9', '#d8d3c7']], arrows: [[2.2, 0, -2.2, 0]], text: [[-2.5, -1.2, 'the preimage of 9']], alt: 'The input that produced a given output.' },
  'mapping': { ...B, pts: [[-2.5, 1.5, '', '#e0813a'], [-2.5, -1.5, '', '#e0813a'], [2.5, 1.5], [2.5, -1.5]], arrows: [[-2.2, 1.5, 2.2, 1.5], [-2.2, -1.5, 2.2, -1.5]], alt: 'A rule shown as arrows from one set to another.' },
  'arrow diagram': { ...B, pts: [[-2.5, 2, '1', '#e0813a'], [-2.5, 0, '2', '#e0813a'], [-2.5, -2, '3', '#e0813a'], [2.5, 2, '3'], [2.5, 0, '4'], [2.5, -2, '5']], arrows: [[-2.2, 2, 2.2, 2], [-2.2, 0, 2.2, 0], [-2.2, -2, 2.2, -2]], alt: 'Two columns of values joined by arrows.' },
  'set of ordered pairs': { ...P, grid: 'dots', pts: [[-2, -1], [0, 1], [1, 2], [3, 0]], note: '{(−2,−1), (0,1), (1,2), (3,0)}', alt: 'A function written as a list of input-output pairs, plotted.' },
  'well-defined': { ...B, pts: [[-2.5, 0, '', '#e0813a'], [2.5, 0]], arrows: [[-2.2, 0, 2.2, 0]], text: [[0, 0.9, 'one arrow'], [0, -1.4, 'no ambiguity']], alt: 'A rule that settles on exactly one answer.' },
  'one input one output': { ...B, pts: [[-2.5, 1.5, '', '#e0813a'], [-2.5, -1.5, '', '#e0813a'], [2.5, 1.5], [2.5, -1.5]], arrows: [[-2.2, 1.5, 2.2, 1.5], [-2.2, -1.5, 2.2, -1.5]], alt: 'The promise a function makes, drawn: one arrow out of each input.' },
  'the fork': { ...B, pts: [[-2.5, 0, '', '#c0504d'], [2.5, 1.8], [2.5, -1.8]], arrows: [[-2.2, 0, 2.2, 1.8, '#c0504d'], [-2.2, 0, 2.2, -1.8, '#c0504d']], alt: 'One input sending two arrows, which is the only thing a function may not do.' },
  'vertical line test': { ...P, curves: [{ f: x => 0.4 * sq(x) - 2 }], lines: [{ x: 2, dash: true, c2: '#e0813a' }], pts: [[2, -0.4]], note: 'one hit', alt: 'A vertical line meeting a curve once, so each input has one output.' },
  'horizontal line test': { ...P, curves: [{ f: x => 0.4 * sq(x) - 2 }], lines: [{ y: 1.6, dash: true, c2: '#e0813a' }], pts: [[3, 1.6], [-3, 1.6]], note: 'two hits', alt: 'A horizontal line meeting a curve twice, so two inputs share an output.' },
  'one-to-one': { ...B, pts: [[-2.5, 1.5, '', '#e0813a'], [-2.5, -1.5, '', '#e0813a'], [2.5, 1.5], [2.5, -1.5]], arrows: [[-2.2, 1.5, 2.2, 1.5], [-2.2, -1.5, 2.2, -1.5]], note: 'no output shared', alt: 'Different inputs always landing on different outputs.' },
  'injective': { ...B, pts: [[-2.5, 1.5, '', '#e0813a'], [-2.5, -1.5, '', '#e0813a'], [2.5, 2.5], [2.5, 0], [2.5, -2.5, '', '#d8d3c7']], arrows: [[-2.2, 1.5, 2.2, 2.5], [-2.2, -1.5, 2.2, 0]], note: 'one-to-one', alt: 'Every output used at most once; some may be unused.' },
  'many-to-one': { ...B, pts: [[-2.5, 2, '', '#e0813a'], [-2.5, 0, '', '#e0813a'], [-2.5, -2, '', '#e0813a'], [2.5, 0]], arrows: [[-2.2, 2, 2.2, 0], [-2.2, 0, 2.2, 0], [-2.2, -2, 2.2, 0]], note: 'sharing is allowed', alt: 'Several inputs landing on the same output, which is permitted.' },
  'onto': { ...B, pts: [[-2.5, 2, '', '#e0813a'], [-2.5, 0, '', '#e0813a'], [-2.5, -2, '', '#e0813a'], [2.5, 1.5], [2.5, -1.5]], arrows: [[-2.2, 2, 2.2, 1.5], [-2.2, 0, 2.2, -1.5], [-2.2, -2, 2.2, -1.5]], note: 'nothing left over', alt: 'Every output is reached by something.' },
  'surjective': { ...B, pts: [[-2.5, 2, '', '#e0813a'], [-2.5, 0, '', '#e0813a'], [-2.5, -2, '', '#e0813a'], [2.5, 1.5], [2.5, -1.5]], arrows: [[-2.2, 2, 2.2, 1.5], [-2.2, 0, 2.2, -1.5], [-2.2, -2, 2.2, -1.5]], note: 'onto', alt: 'The formal name for a rule that reaches every output.' },
  'bijective': { ...B, pts: [[-2.5, 1.5, '', '#e0813a'], [-2.5, -1.5, '', '#e0813a'], [2.5, 1.5], [2.5, -1.5]], arrows: [[-2.2, 1.5, 2.2, 1.5], [-2.2, -1.5, 2.2, -1.5]], note: 'a perfect pairing', alt: 'One arrow out of each input and one into each output.' },
  'function notation': { ...B, text: [[0, 0.8, 'f(x)', '#16283f', 20], [0, -1.2, 'the output f gives to x']], alt: 'The symbol naming the output a rule gives an input.' },
  'f(x)': { ...B, text: [[0, 0.8, 'f(x) = 2x + 1', '#16283f', 16], [0, -1.2, 'not f times x']], alt: 'A rule written in function notation.' },
  'evaluating': { ...B, pts: [[-2.8, 0, '4', '#e0813a'], [2.8, 0, '9']], arrows: [[-2.4, 0, 2.4, 0]], text: [[0, 0.8, 'f(x)=2x+1'], [0, -1.4, 'input given, output wanted']], alt: 'Putting a number in and computing what comes out.' },
  'solving for the input': { ...B, pts: [[-2.8, 0, '4', '#d8d3c7'], [2.8, 0, '9', '#e0813a']], arrows: [[2.4, 0, -2.4, 0, '#a25d2a']], text: [[0, -1.4, 'output given, input wanted']], alt: 'Running the arrow backwards: the answer is known and the input is not.' },
  'independent variable': { ...P, curves: [{ f: x => 0.6 * x + 1 }], axisHi: 'x', text: [[3.4, -0.9, 'x', '#a25d2a', 11]], note: 'the one you choose', alt: 'The input, plotted across, chosen freely.' },
  'dependent variable': { ...P, curves: [{ f: x => 0.6 * x + 1 }], axisHi: 'y', text: [[0.9, 3.6, 'y', '#a25d2a', 11]], note: 'the one that follows', alt: 'The output, plotted up, determined by the input.' },
  'argument': { ...B, text: [[0, 0.6, 'f( 4 )', '#16283f', 20], [0, -1.3, 'the thing inside the brackets']], alt: 'What a rule is applied to.' },
  'value of a function': { ...B, text: [[0, 0.6, 'f(4) = 9', '#16283f', 18], [0, -1.3, 'the number that comes out']], alt: 'The output at a particular input.' },
  'substituting into a rule': { ...B, text: [[0, 1.2, 'f(⬚) = 2⬚ + 1', '#16283f', 15], [0, -0.3, 'f(4) = 2(4) + 1', '#10796e', 15], [0, -1.7, 'whatever arrives goes in every blank']], alt: 'Putting an input into every blank in a rule.' },
  'table of values': { ...P, grid: 'dots', pts: [[0, 1], [1, 3], [2, 5], [3, 7]], note: '0→1, 1→3, 2→5, 3→7', alt: 'A list of input-output pairs, plotted as points.' },
  'graph of a function': { ...P, curves: [{ f: x => 2 * x - 1 }], pts: [[1, 1], [2, 3]], alt: 'Every input-output pair drawn at once.' },
  'four representations': { ...B, text: [[-2.6, 1.6, 'words'], [2.6, 1.6, 'table'], [-2.6, -1.6, 'formula'], [2.6, -1.6, 'graph'], [0, 0, 'one rule', '#10796e', 12]], arrows: [[-2, 1.2, -0.6, 0.3], [2, 1.2, 0.6, 0.3], [-2, -1.2, -0.6, -0.3], [2, -1.2, 0.6, -0.3]], alt: 'The same rule held four ways, each pointing to the same thing.' },
  'natural domain': { line: true, spans: [[-5, 0, 'out'], [0, 5]], marks: [{ x: 0 }], note: 'everything the algebra allows', alt: 'The largest set of inputs a formula will accept.' },
  'implied domain': { line: true, spans: [[-5, 2], [2, 5]], marks: [{ x: 2, open: true }], note: 'stated by the formula alone', alt: 'The domain a formula implies without anyone writing it down.' },
  'contextual domain': { line: true, from: -2, to: 12, spans: [[-2, 0, 'out'], [0, 10], [10, 12, 'out']], marks: [{ x: 0 }, { x: 10 }], note: 'set by the situation', alt: 'A domain narrowed by what the quantity means, not by the algebra.' },
  'restricted domain': { ...P, curves: [{ f: x => x >= 0 ? 0.4 * sq(x) - 2 : NaN }], note: 'half the curve discarded', alt: 'A rule deliberately given fewer inputs, so only part of its curve is drawn.' },
  'excluded value': { line: true, spans: [[-5, 3], [3, 5]], marks: [{ x: 3, open: true }], note: 'one point removed', alt: 'A single input the rule refuses, shown as a hollow endpoint.' },
  'division by zero': { ...P, curves: [{ f: x => 1 / x }], note: 'nothing at x = 0', alt: 'A curve that breaks into two branches where its denominator vanishes.' },
  'even root of a negative': { ...P, curves: [{ f: x => Math.sqrt(x) }], shade: { left: 0 }, note: 'nothing to the left', alt: 'A square root drawn only where its input is not negative.' },
  'interval notation': { line: true, spans: [[-2, 3]], marks: [{ x: -2 }, { x: 3, open: true }], note: '[−2, 3)', alt: 'A stretch of the line written with brackets, one end included and one not.' },
  'open interval': { line: true, spans: [[-2, 3]], marks: [{ x: -2, open: true }, { x: 3, open: true }], note: '(−2, 3)', alt: 'Both endpoints excluded, drawn hollow.' },
  'closed interval': { line: true, spans: [[-2, 3]], marks: [{ x: -2 }, { x: 3 }], note: '[−2, 3]', alt: 'Both endpoints included, drawn filled.' },
  'half-open interval': { line: true, spans: [[-2, 3]], marks: [{ x: -2 }, { x: 3, open: true }], note: '[−2, 3)', alt: 'One endpoint included and the other not.' },
  'union of intervals': { line: true, spans: [[-5, -1], [2, 5]], marks: [{ x: -1, open: true }, { x: 2, open: true }], note: 'two separate stretches', alt: 'Two stretches of the line taken together, with a gap between them.' },
  'unbounded interval': { line: true, spans: [[1, 5]], marks: [{ x: 1 }], note: '[1, ∞)', alt: 'A stretch with one end and no other, running on without limit.' },
  'set-builder notation': { ...B, text: [[0, 0.6, '{ x : x > 2 }', '#16283f', 16], [0, -1.2, 'the set of x such that x is more than 2']], alt: 'A set written as the condition its members satisfy.' },

  /* ------------------------------------------------ 5. families of curves */
  'constant function': { ...P, curves: [{ f: () => 2 }], note: 'f(x) = 2', alt: 'A flat line: every input gives the same output.' },
  'identity function': { ...P, curves: [{ f: x => x }], note: 'f(x) = x', alt: 'The line through the origin at forty-five degrees, returning every input unchanged.' },
  'linear function': { ...P, curves: [{ f: x => 0.8 * x + 1 }], note: 'f(x) = 0.8x + 1', alt: 'A straight line with a fixed steepness.' },
  'affine function': { ...P, curves: [{ f: x => 0.8 * x + 1 }], pts: [[0, 1]], note: 'a line not through the origin', alt: 'A straight line shifted off the origin by a constant.' },
  'quadratic function': { ...P, curves: [{ f: x => 0.5 * sq(x) - 2 }], note: 'f(x) = 0.5x² − 2', alt: 'A parabola, falling to a lowest point and rising again.' },
  'parabola': { ...P, curves: [{ f: x => 0.5 * sq(x) - 2 }], alt: 'The U-shaped curve a quadratic rule draws.' },
  'vertex of a parabola': { ...P, curves: [{ f: x => 0.5 * sq(x) - 2 }], pts: [[0, -2, '(0, −2)', '#e0813a']], alt: 'The single turning point of a parabola.' },
  'axis of symmetry': { ...P, curves: [{ f: x => 0.5 * sq(x - 1) - 2 }], lines: [{ x: 1, dash: true, c2: '#e0813a' }], alt: 'The vertical line a parabola is a mirror image about.' },
  'completing the square': { ...P, curves: [{ f: x => sq(x - 1) - 3 }], pts: [[1, -3, '(1, −3)', '#e0813a']], note: '(x − 1)² − 3', alt: 'A quadratic rewritten so its turning point can be read straight off.' },
  'vertex form': { ...P, curves: [{ f: x => sq(x - 1) - 3 }], pts: [[1, -3]], note: 'a(x − h)² + k', alt: 'The form of a quadratic that names its vertex directly.' },
  'factored form': { ...P, curves: [{ f: x => 0.6 * (x + 2) * (x - 3) }], pts: [[-2, 0], [3, 0]], note: 'a(x + 2)(x − 3)', alt: 'The form that names the two inputs giving zero.' },
  'root': { ...P, curves: [{ f: x => 0.6 * (x + 2) * (x - 3) }], pts: [[-2, 0, '', '#e0813a'], [3, 0, '', '#e0813a']], alt: 'An input at which the output is zero.' },
  'zero of a function': { ...P, curves: [{ f: x => 0.6 * (x + 2) * (x - 3) }], pts: [[-2, 0, '', '#e0813a'], [3, 0, '', '#e0813a']], note: 'where the curve crosses', alt: 'The same idea as a root: where the graph meets the horizontal axis.' },
  'discriminant': { ...P, curves: [{ f: x => 0.5 * sq(x) - 2 }, { f: x => 0.5 * sq(x), c2: '#e0813a' }, { f: x => 0.5 * sq(x) + 1.5, c2: '#c0504d' }], note: 'two roots, one, none', alt: 'Three parabolas: one crossing twice, one touching once, one missing the axis entirely.' },
  'repeated root': { ...P, curves: [{ f: x => 0.6 * sq(x - 1) }], pts: [[1, 0, '', '#e0813a']], note: 'touches without crossing', alt: 'A curve meeting the axis at one point and turning back.' },
  'cubic function': { ...P, curves: [{ f: x => 0.12 * x * sq(x) - 0.8 * x }], note: 'f(x) = 0.12x³ − 0.8x', alt: 'A curve with up to two turning points, running from bottom left to top right.' },
  'quartic function': { ...P, curves: [{ f: x => 0.06 * sq(sq(x)) - 0.8 * sq(x) + 1 }], note: 'two dips', alt: 'A curve with up to three turning points, both ends heading the same way.' },
  'polynomial': { ...P, curves: [{ f: x => 0.12 * x * sq(x) - 0.8 * x }], note: 'sums of powers of x', alt: 'A smooth curve with no breaks, built from whole-number powers.' },
  'degree': { ...P, curves: [{ f: x => x, c2: '#d8d3c7' }, { f: x => 0.4 * sq(x) - 1, c2: '#5d6b7d' }, { f: x => 0.12 * x * sq(x) - 0.8 * x }], note: '1, then 2, then 3', alt: 'Three curves of increasing degree, each allowed one more turn than the last.' },
  'leading coefficient': { ...P, curves: [{ f: x => 0.5 * sq(x) - 2 }, { f: x => -0.5 * sq(x) + 2, c2: '#e0813a' }], note: 'its sign decides the ends', alt: 'Two parabolas with opposite leading signs, one opening up and one down.' },
  'end behaviour': { ...P, curves: [{ f: x => 0.12 * x * sq(x) }], arrows: [[3.6, 2.6, 4.4, 4.2, '#e0813a'], [-3.6, -2.6, -4.4, -4.2, '#e0813a']], note: 'what happens far out', alt: 'A curve with arrows showing where each end is heading.' },
  'turning point': { ...P, curves: [{ f: x => 0.12 * x * sq(x) - 0.9 * x }], pts: [[-1.58, 0.95, '', '#e0813a'], [1.58, -0.95, '', '#e0813a']], alt: 'A place where a curve stops rising and starts falling, or the reverse.' },
  'local maximum': { ...P, curves: [{ f: x => 0.12 * x * sq(x) - 0.9 * x }], pts: [[-1.58, 0.95, 'highest nearby', '#e0813a']], alt: 'A peak: higher than everything immediately around it.' },
  'local minimum': { ...P, curves: [{ f: x => 0.12 * x * sq(x) - 0.9 * x }], pts: [[1.58, -0.95, 'lowest nearby', '#e0813a']], alt: 'A dip: lower than everything immediately around it.' },
  'global maximum': { ...P, curves: [{ f: x => -0.4 * sq(x) + 3 }], pts: [[0, 3, 'highest anywhere', '#e0813a']], alt: 'The highest point the curve ever reaches.' },
  'global minimum': { ...P, curves: [{ f: x => 0.4 * sq(x) - 3 }], pts: [[0, -3, 'lowest anywhere', '#e0813a']], alt: 'The lowest point the curve ever reaches.' },
  'rational function': { ...P, curves: [{ f: x => 1 / (x - 1) }], lines: [{ x: 1, dash: true, c2: '#c0504d' }], note: 'one polynomial over another', alt: 'A curve breaking into branches where its denominator vanishes.' },
  'asymptote': { ...P, curves: [{ f: x => 1 / x }], lines: [{ x: 0, dash: true, c2: '#c0504d' }, { y: 0, dash: true, c2: '#c0504d' }], alt: 'A line a curve approaches without ever reaching.' },
  'vertical asymptote': { ...P, curves: [{ f: x => 1 / (x - 1) }], lines: [{ x: 1, dash: true, c2: '#c0504d' }], alt: 'An upright line the curve climbs alongside without touching.' },
  'horizontal asymptote': { ...P, curves: [{ f: x => 2 + 3 / x }], lines: [{ y: 2, dash: true, c2: '#c0504d' }], note: 'settles at y = 2', alt: 'A level the curve settles toward far out.' },
  'oblique asymptote': { ...P, curves: [{ f: x => x + 1 / x }], lines: [{ m: 1, c: 0, dash: true, c2: '#c0504d' }], alt: 'A slanted line the curve approaches at both ends.' },
  'hole in a graph': { ...P, curves: [{ f: x => x === 1 ? NaN : x + 1 }], open: [[1, 2]], alt: 'A single point missing from an otherwise unbroken curve.' },
  'reciprocal function': { ...P, curves: [{ f: x => 1 / x }], note: 'f(x) = 1/x', alt: 'Two branches, each approaching both axes without touching.' },
  'hyperbola (rectangular)': { ...P, curves: [{ f: x => 2 / x }], note: 'xy = 2', alt: 'The two-branch curve whose coordinates multiply to a constant.' },
  'square root function': { ...P, curves: [{ f: x => 2 * Math.sqrt(x) }], pts: [[0, 0]], note: 'starts at the origin', alt: 'A curve rising from the origin and flattening as it goes.' },
  'radical function': { ...P, curves: [{ f: x => 2 * Math.sqrt(x + 3) - 1 }], note: 'a root, shifted', alt: 'A root curve moved off the origin.' },
  'cube root function': { ...P, curves: [{ f: x => 2 * Math.cbrt(x) }], note: 'accepts negatives', alt: 'A curve through the origin defined for negative inputs as well as positive.' },
  'absolute value function': { ...P, curves: [{ f: x => Math.abs(x) - 1 }], pts: [[0, -1, 'corner', '#e0813a']], alt: 'Two straight pieces meeting at a sharp corner.' },
  'piecewise function': { ...P, curves: [{ f: x => x < 0 ? -1 : 0.8 * x }], open: [[0, -1]], pts: [[0, 0]], alt: 'A rule made of different pieces on different stretches.' },
  'step function': { ...P, curves: [{ f: x => Math.floor(x) }], note: 'jumps at each whole number', alt: 'A staircase, flat between jumps.' },
  'floor function': { ...P, curves: [{ f: x => Math.floor(x) }], note: 'round down', alt: 'A staircase taking the whole number at or below the input.' },
  'ceiling function': { ...P, curves: [{ f: x => Math.ceil(x) }], note: 'round up', alt: 'A staircase taking the whole number at or above the input.' },
  'signum function': { ...P, curves: [{ f: x => Math.sign(x) * 2 }], open: [[0, 2], [0, -2]], pts: [[0, 0]], note: 'the sign only', alt: 'A rule returning minus two, zero or two according to the sign of the input.' },
  'exponential function': { ...P, curves: [{ f: x => Math.pow(2, x) - 2 }], note: 'f(x) = 2ˣ − 2', alt: 'A curve whose steepness grows with its own height.' },
  'base': { ...P, curves: [{ f: x => Math.pow(2, x) - 2 }, { f: x => Math.pow(3, x) - 2, c2: '#e0813a' }], note: 'base 2, then base 3', alt: 'Two exponential curves, the larger base climbing faster.' },
  'exponential growth': { ...P, curves: [{ f: x => Math.pow(1.8, x) - 2 }], note: 'multiplies each step', alt: 'A curve rising ever more steeply.' },
  'exponential decay': { ...P, curves: [{ f: x => 4 * Math.pow(0.55, x) - 2 }], note: 'shrinks each step', alt: 'A curve falling toward a level it never reaches.' },
  'doubling time': { ...P, x0: -1, x1: 9, y0: -1, y1: 9, curves: [{ f: x => Math.pow(2, x / 3) }], pts: [[0, 1], [3, 2], [6, 4]], note: 'every 3 units', alt: 'An exponential curve with the points where it has doubled marked.' },
  'half-life': { ...P, x0: -1, x1: 9, y0: -1, y1: 9, curves: [{ f: x => 8 * Math.pow(0.5, x / 3) }], pts: [[0, 8], [3, 4], [6, 2]], note: 'halves every 3 units', alt: 'A decay curve with the points where it has halved marked.' },
  'the number e': { ...P, curves: [{ f: x => Math.exp(x) - 2 }], note: 'e ≈ 2.718', alt: 'The exponential curve whose steepness equals its own height.' },
  'logarithm': { ...P, curves: [{ f: x => Math.log(x) }], pts: [[1, 0]], note: 'the inverse of an exponential', alt: 'A curve crossing at one, rising ever more slowly.' },
  'logarithmic function': { ...P, curves: [{ f: x => Math.log2(x) }], lines: [{ x: 0, dash: true, c2: '#c0504d' }], alt: 'A curve defined only for positive inputs, with the vertical axis as an asymptote.' },
  'natural logarithm': { ...P, curves: [{ f: x => Math.log(x) }], pts: [[Math.E, 1, 'at e, one']], alt: 'The logarithm to base e.' },
  'common logarithm': { ...P, x0: -1, x1: 12, y0: -2, y1: 3, curves: [{ f: x => Math.log10(x) }], pts: [[1, 0], [10, 1]], note: 'base 10', alt: 'The logarithm to base ten, reaching one at ten.' },
  'log laws': { ...B, text: [[0, 1.2, 'log(ab) = log a + log b', '#16283f', 13], [0, -0.2, 'log(a/b) = log a − log b', '#16283f', 13], [0, -1.6, 'log(aⁿ) = n log a', '#16283f', 13]], alt: 'The three rules turning multiplication into addition.' },
  'sine': { ...P, x0: -6.5, x1: 6.5, y0: -2.5, y1: 2.5, curves: [{ f: Math.sin }], note: 'sin x', alt: 'A wave starting at zero and rising first.' },
  'cosine': { ...P, x0: -6.5, x1: 6.5, y0: -2.5, y1: 2.5, curves: [{ f: Math.cos }], note: 'cos x', alt: 'The same wave shifted, starting at its peak.' },
  'tangent function': { ...P, x0: -4.7, x1: 4.7, y0: -4, y1: 4, curves: [{ f: x => Math.tan(x) }], lines: [{ x: Math.PI / 2, dash: true, c2: '#c0504d' }, { x: -Math.PI / 2, dash: true, c2: '#c0504d' }], alt: 'A curve repeating between vertical asymptotes.' },
  'amplitude': { ...P, x0: -6.5, x1: 6.5, y0: -3.5, y1: 3.5, curves: [{ f: x => 2.5 * Math.sin(x) }], segs: [[Math.PI / 2, 0, Math.PI / 2, 2.5, '#e0813a', false, 3]], note: 'height from the middle', alt: 'A wave with its distance from the centre line to a peak marked.' },
  'period': { ...P, x0: -1, x1: 13, y0: -2.5, y1: 2.5, curves: [{ f: x => Math.sin(x) }], segs: [[0, -1.8, 2 * Math.PI, -1.8, '#e0813a', false, 3]], note: 'one full cycle', alt: 'A wave with the horizontal length of one complete repeat marked.' },
  'phase shift': { ...P, x0: -6.5, x1: 6.5, y0: -2.5, y1: 2.5, curves: [{ f: Math.sin, c2: '#d8d3c7' }, { f: x => Math.sin(x - 1.2) }], note: 'the same wave, moved', alt: 'A wave and a copy of it shifted sideways.' },
  'frequency (of a wave)': { ...P, x0: -6.5, x1: 6.5, y0: -2.5, y1: 2.5, curves: [{ f: Math.sin, c2: '#d8d3c7' }, { f: x => Math.sin(3 * x) }], note: 'three cycles instead of one', alt: 'Two waves, one repeating three times as often.' },
  'radian measure': { ...P, x0: -2.2, x1: 2.2, y0: -2.2, y1: 2.2, circles: [{ cx: 0, cy: 0, r: 1.5 }], segs: [[0, 0, 1.5, 0, '#5d6b7d', false, 1.6], [0, 0, 0.81, 1.26, '#e0813a', false, 2]], note: 'arc equal to radius', alt: 'An angle measured by the arc it cuts, in units of the radius.' },
  'degree measure': { ...P, x0: -2.2, x1: 2.2, y0: -2.2, y1: 2.2, circles: [{ cx: 0, cy: 0, r: 1.5 }], segs: [[0, 0, 1.5, 0, '#5d6b7d', false, 1.6], [0, 0, 0, 1.5, '#e0813a', false, 2]], note: '90° of 360', alt: 'An angle measured as a fraction of a full turn split into 360 parts.' },
  'unit circle': { ...P, x0: -2.2, x1: 2.2, y0: -2.2, y1: 2.2, circles: [{ cx: 0, cy: 0, r: 1 }], pts: [[0.707, 0.707, '(cos, sin)']], segs: [[0, 0, 0.707, 0.707, '#e0813a', false, 1.6]], alt: 'The circle of radius one, on which every point gives a cosine and a sine.' },
  'periodicity': { ...P, x0: -1, x1: 13, y0: -2.5, y1: 2.5, curves: [{ f: Math.sin }], lines: [{ x: 2 * Math.PI, dash: true, c2: '#e0813a' }, { x: 4 * Math.PI, dash: true, c2: '#e0813a' }], note: 'repeats forever', alt: 'A wave repeating the same shape at fixed intervals.' },
  'sinusoid': { ...P, x0: -6.5, x1: 6.5, y0: -3.5, y1: 3.5, curves: [{ f: x => 2 * Math.sin(1.5 * x + 0.6) }], note: 'any wave of this shape', alt: 'A general wave, with its own height, repeat length and starting position.' }
};
