// How each concept can be drawn, where it cannot be drawn directly.
//
// Four verdicts. Anything not listed here is `direct`: the concept itself is a
// picture, and drawing it is the whole explanation. The exceptions are what
// this file records, because they are where a course has to do something other
// than show you.
//
//   frames    a single still cannot carry it; it needs a sequence, because the
//             concept is a process rather than an object
//   instance  only a particular case can be drawn. The picture is an example
//             of the idea, never the idea, and a reader who mistakes one for
//             the other has learned the example
//   none      no picture is possible. It must be argued in words or symbols,
//             and pretending otherwise is where visual teaching starts lying
//
// The verdicts are judgements, not facts, and they are deliberately strict:
// "you could draw something suggestive" is not the same as "the concept is
// drawable". Stage 13 is where the strictness earns its keep.

export const HOW = {
  // ---- stage 1-3: the plane is the concept, so almost nothing is excepted --
  'convention (input first)': 'frames',
  'the pair (3, 1) against (1, 3)': 'frames',
  'equal scaling': 'frames',
  'distorted scaling': 'frames',
  'betweenness': 'instance',
  'a line as a set of points': 'instance',
  'linear programming': 'instance',
  'objective function': 'instance',

  // ---- stage 4: the function idea ----------------------------------------
  'relation': 'instance',
  'function': 'instance',
  'rule': 'instance',
  'well-defined': 'instance',
  'function notation': 'none',
  'f(x)': 'none',
  'set-builder notation': 'none',
  'interval notation': 'instance',
  'argument': 'instance',
  'value of a function': 'instance',
  'substituting into a rule': 'frames',
  'evaluating': 'frames',
  'solving for the input': 'frames',
  'four representations': 'frames',
  'table of values': 'instance',
  'independent variable': 'instance',
  'dependent variable': 'instance',

  // ---- stage 5: families --------------------------------------------------
  'base': 'instance',
  'degree': 'instance',
  'leading coefficient': 'instance',
  'log laws': 'none',
  'the number e': 'frames',
  'factored form': 'none',
  'completing the square': 'frames',
  'discriminant': 'frames',
  'radian measure': 'frames',
  'degree measure': 'instance',

  // ---- stage 6: transformations are processes -----------------------------
  'transformation': 'frames',
  'translation': 'frames',
  'horizontal shift': 'frames',
  'vertical shift': 'frames',
  'shift against the sign': 'frames',
  'reflection': 'frames',
  'stretch': 'frames',
  'compression': 'frames',
  'dilation': 'frames',
  'order of transformations': 'frames',
  'composition of transformations': 'frames',
  'rotation about the origin': 'frames',
  'shear': 'frames',
  'mapping notation': 'none',
  'transformation matrix': 'none',
  'scale factor': 'instance',

  // ---- stage 7 ------------------------------------------------------------
  'parametrisation': 'frames',
  'eliminating the parameter': 'none',
  'parameter': 'frames',
  'polar to Cartesian conversion': 'frames',
  'degenerate conic': 'instance',

  // ---- stage 8 ------------------------------------------------------------
  'causation against correlation': 'instance',
  'goodness of fit': 'instance',
  'least squares': 'frames',
  'sampling': 'instance',

  // ---- stage 9: change is a process, and limits are the hard case ---------
  'approaching a value': 'frames',
  'arbitrarily close': 'frames',
  'shrinking the interval': 'frames',
  'limit': 'frames',
  'left-hand limit': 'frames',
  'right-hand limit': 'frames',
  'two-sided limit': 'frames',
  'existence of a limit': 'frames',
  'limit at infinity': 'frames',
  'instantaneous rate': 'frames',
  'neighbourhood': 'instance',
  'indeterminate form': 'instance',
  'zero over zero': 'instance',
  'factor and cancel': 'none',
  'epsilon': 'instance',
  'delta (the tolerance)': 'instance',
  'h notation': 'none',
  'delta': 'frames',
  'increment': 'frames',
  'change': 'frames',
  'new minus old': 'frames',
  'signed change': 'frames',

  // ---- stage 10: the rules are algebra, whatever the picture suggests -----
  'differentiation': 'frames',
  'derivative': 'frames',
  'derivative at a point': 'frames',
  'prime notation': 'none',
  'Leibniz notation': 'none',
  'dy/dx': 'none',
  'operator notation': 'none',
  'power rule': 'instance',
  'constant rule': 'instance',
  'constant multiple rule': 'instance',
  'sum rule': 'instance',
  'difference rule': 'instance',
  'quotient rule': 'none',
  'implicit differentiation': 'none',
  'logarithmic differentiation': 'none',
  'derivative of an inverse function': 'instance',
  'higher derivatives': 'instance',
  'differentiability implies continuity': 'instance',
  'first derivative test': 'frames',
  'second derivative test': 'frames',
  'monotonic': 'instance',
  'optimisation': 'frames',
  'constraint': 'instance',
  'related rates': 'frames',
  'elasticity': 'instance',
  'linearisation': 'frames',
  'differential': 'instance',
  "Newton's method": 'frames',
  'Taylor polynomial': 'frames',
  'Maclaurin series': 'frames',
  'radius of convergence': 'instance',
  "L'Hopital's rule": 'instance',

  // ---- stage 11: the techniques are algebra; the objects are pictures -----
  'antiderivative': 'instance',
  'indefinite integral': 'instance',
  'constant of integration': 'frames',
  'integral sign': 'none',
  'variable of integration': 'none',
  'integrand': 'none',
  'limit of Riemann sums': 'frames',
  'integrability': 'instance',
  'numerical integration': 'frames',
  'substitution': 'none',
  'u-substitution': 'none',
  'integration by parts': 'instance',
  'partial fractions': 'none',
  'trigonometric substitution': 'instance',
  'reduction formula': 'none',
  'improper integral': 'frames',
  'convergent integral': 'frames',
  'divergent integral': 'frames',
  'separable differential equation': 'none',
  'initial condition': 'instance',
  'particular solution': 'instance',
  "Euler's method": 'frames',
  'net change theorem': 'instance',
  'first fundamental theorem': 'frames',
  'second fundamental theorem': 'frames',
  'accumulation function': 'frames',

  // ---- stage 12: three dimensions on a flat page --------------------------
  'matrix': 'none',
  'matrix transformation': 'frames',
  'linear combination': 'frames',
  'span': 'instance',
  'basis': 'instance',
  'linear independence': 'instance',
  'eigenvalue': 'instance',
  'change of variables': 'frames',
  'order of integration': 'frames',
  'iterated integral': 'frames',
  'Jacobian': 'instance',
  'polar substitution': 'none',
  'conservative field': 'instance',
  'potential function': 'instance',
  'flux': 'instance',
  'quadric surface': 'instance',
  'right-handed system': 'instance',
  'octant': 'instance',
  'coordinate space': 'instance',
  'three-dimensional space': 'instance',
  'triple integral': 'instance',
  'surface integral': 'instance',
  'Lagrange multiplier': 'frames',
  'critical point in 3D': 'instance',

  // ---- stage 13: where it stops --------------------------------------------
  'counterexample': 'instance',
  'pathological function': 'instance',
  'Dirichlet function': 'none',
  'nowhere continuous': 'none',
  'Weierstrass function': 'frames',
  'nowhere differentiable': 'frames',
  'everywhere continuous': 'instance',
  'fractal': 'frames',
  'self-similarity': 'frames',
  'Koch snowflake': 'frames',
  'Cantor set': 'frames',
  'Hausdorff dimension': 'instance',
  'measure': 'instance',
  'measure zero': 'frames',
  'almost everywhere': 'none',
  'Riemann integrable': 'frames',
  'Lebesgue integral': 'instance',
  'non-integrable function': 'none',
  'elementary function': 'none',
  'non-elementary antiderivative': 'instance',
  "Liouville's theorem": 'none',
  'closed form': 'none',
  'algebraic number': 'none',
  'transcendental number': 'none',
  'countable set': 'instance',
  'uncountable set': 'none',
  'dense set': 'instance',
  'nowhere dense': 'instance',
  'completeness of the reals': 'none',
  'supremum': 'instance',
  'infimum': 'instance',
  'bounded sequence': 'instance',
  'convergent sequence': 'frames',
  'divergent sequence': 'frames',
  'pointwise convergence': 'frames',
  'uniform convergence': 'frames',
  'rigour': 'none',
  'formal proof': 'none',
  'intuition against proof': 'none',
  'the limits of visualisation': 'none',
  'higher-dimensional intuition': 'none',
  'axiom': 'none',
  'definition': 'none',
  'theorem': 'none',
  'lemma': 'none',
  'corollary': 'none',
  'necessary and sufficient': 'none',
  'existence proof': 'none',
  'constructive proof': 'none',
  'proof by contradiction': 'none'
};

export const LEGEND = [
  ['direct', 'The concept is a picture. Drawing it is the explanation.'],
  ['frames', 'A process, not an object. It needs a sequence, which is what the labs in the book are for.'],
  ['instance', 'Only a particular case can be drawn. The picture is an example of the idea, never the idea.'],
  ['none', 'No picture is possible. It has to be argued in words or symbols.']
];
