// Writes the learner's copy of the pilot boards from the founder's Factory
// selections.
//
// Why this is a build step and not an import. The option files are authoring
// documents: every board object holds the rejected variants alongside the chosen
// ones, and every variant holds the note explaining why it was built that way.
// Importing a board into the app therefore shipped all of it. Filtering at
// runtime does not help, because a bundler cannot drop properties of an object
// literal that something references. The production bundle contained rejected
// readings and lines like "Rebuilt 2026-08-09 after the founder reported that
// section 3's interactions did not work".
//
// So the filtering happens here, before the bundler sees anything, and the app
// imports the result. What a learner is served is now a different file from what
// the Factory edits, and only the chosen variants cross over.
//
// Runs from prebuild and predev, so it cannot fall behind the selections.

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { func0, selections as selButton, finalised as finButton } from '../src/factory/func0-options.js';
import { func1, selections as selMachine, finalised as finMachine } from '../src/factory/func1-options.js';
import { area, selections as selArea, finalised as finArea } from '../src/factory/area-options.js';
import { plane, selections as selPlane, finalised as finPlane } from '../src/factory/plane-options.js';
import { plot, selections as selPlot, finalised as finPlot } from '../src/factory/plot-options.js';
import { lineSlope, selections as selLineSlope, finalised as finLineSlope } from '../src/factory/line-slope-options.js';

const PILOT = [
  { bb: func0, sel: selButton, fin: finButton, marker: 'Machines' },
  { bb: func1, sel: selMachine, fin: finMachine, marker: 'Rules' },
  { bb: area, sel: selArea, fin: finArea, marker: 'Surface' },
  { bb: plane, sel: selPlane, fin: finPlane, marker: 'Position' },
  { bb: plot, sel: selPlot, fin: finPlot, marker: 'Graph' },
  { bb: lineSlope, sel: selLineSlope, fin: finLineSlope, marker: 'Slope' }
];

const chosen = (list, sel, fin) => (list || []).filter(v => sel[v.code] || fin[v.code]);
// note is authoring reasoning. code is the Factory's handle for a variant and
// means nothing to a learner, but it is kept: it is how the founder names a
// thing when asking for a change, and it costs a few bytes.
const strip = ({ note, ...rest }) => rest;

const boards = PILOT.map(({ bb, sel, fin, marker }) => {
  const floors = bb.sections.map(section => {
    const reading = chosen(section.readings, sel, fin)[0];
    if (!reading) return null;
    // All chosen figures, not just the first. The founder kept two interactions
    // on two of the Machine sections deliberately, and taking [0] silently threw
    // the second away.
    const stages = chosen(section.interactions, sel, fin).map(strip);
    return {
      text: reading.text,
      name: section.name,
      stages,
      exercises: chosen(section.exercises, sel, fin).map(strip)
    };
  }).filter(Boolean);

  return {
    id: bb.id,
    title: bb.title,
    marker,
    fromFactory: true,
    floors,
    workshops: chosen(bb.workshops, sel, fin).map(strip)
  };
}).filter(b => b.floors.length);

const out = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'lib', 'content', 'pilot.generated.js');
writeFileSync(out, `// GENERATED by scripts/build-pilot.mjs. Do not edit.
// The pilot boards as the founder selected them, with authoring notes and
// unchosen variants removed. Regenerate by running a build; it is a prebuild
// step, so it cannot fall behind the Factory.
export const pilotBoards = ${JSON.stringify(boards, null, 2)};
`, 'utf8');

const sections = boards.reduce((n, b) => n + b.floors.length, 0);
const checks = boards.reduce((n, b) => n + b.floors.reduce((m, f) => m + f.exercises.length, 0), 0);
console.log(`pilot: ${boards.length} boards, ${sections} sections, ${checks} checks, ${boards.reduce((n, b) => n + b.workshops.length, 0)} workshops`);
for (const b of boards) console.log(`   ${b.id}  ${b.title}  (${b.floors.length} sections)`);
