// Build crawler entry points from the same registries and generated library
// that the learner-facing site uses. This avoids another hardcoded chapter
// count or book list drifting away from what is actually published.

import { readdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildSiteRoutes } from './site-routes.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const PUBLIC = join(ROOT, 'public');
const LIBRARY = join(PUBLIC, 'library');
const ORIGIN = 'https://qubix.university';

const libraryPages = (await readdir(LIBRARY))
  .filter(file => file.endsWith('.html'))
  .sort()
  .map(file => `/library/${file}`);

const inventory = buildSiteRoutes(libraryPages);
const paths = inventory.filter(item => item.indexable).map(item => item.url);

const xml = value => value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${paths.map(path => `  <url><loc>${xml(ORIGIN + path)}</loc></url>`).join('\n')}
</urlset>
`;
const robots = `User-agent: *
Allow: /

Sitemap: ${ORIGIN}/sitemap.xml
`;

await writeFile(join(PUBLIC, 'sitemap.xml'), sitemap, 'utf8');
await writeFile(join(PUBLIC, 'robots.txt'), robots, 'utf8');

const grouped = inventory.reduce((groups, item) => {
  if (!groups.has(item.area)) groups.set(item.area, []);
  groups.get(item.area).push(item);
  return groups;
}, new Map());
const counts = Object.fromEntries(
  ['public', 'preview', 'legacy', 'internal'].map(visibility => [
    visibility,
    inventory.filter(item => item.visibility === visibility).length
  ])
);
const inventoryDocument = `# Complete Site Route Inventory

Generated by \`scripts/build-seo.mjs\` from the application registries. Do not edit by hand.

| Measure | Count |
|---|---:|
| All finite test routes | ${inventory.length} |
| Canonical public routes in the sitemap | ${paths.length} |
| Live preview routes, excluded from search | ${counts.preview} |
| Compatibility aliases, excluded from search | ${counts.legacy} |
| Internal authoring routes, excluded from production search | ${counts.internal} |

“Excluded from search” does not mean forgotten: every entry below remains part of the route audit and smoke-test inventory. Arbitrary search terms such as \`?mode=wiki&q=...\` are input states rather than finite pages and are tested as behaviour, not enumerated as URLs.

${[...grouped].map(([area, items]) => `## ${area}

| URL | Visibility | Search |
|---|---|---|
${items.map(item => `| \`${item.url}\` | ${item.visibility} | ${item.indexable ? 'yes' : 'no'} |`).join('\n')}`).join('\n\n')}
`;
await writeFile(join(ROOT, 'docs', 'ROUTE-INVENTORY.md'), inventoryDocument, 'utf8');

const index = await readFile(join(ROOT, 'index.html'), 'utf8');
if (/Variables and Rates of Change \| Qubix University<\/title>/.test(index)) {
  throw new Error('index.html still publishes the mathematics prototype as the site title.');
}

for (const file of libraryPages) {
  const html = await readFile(join(PUBLIC, file.replace(/^\//, '')), 'utf8');
  for (const required of ['name="description"', 'rel="canonical"', 'property="og:title"']) {
    if (!html.includes(required)) throw new Error(`${file} is missing ${required}.`);
  }
}

console.log(`SEO files built: ${paths.length} canonical URLs, ${inventory.length} total test routes, ${libraryPages.length} library pages`);
