// Production deploy. package.json has referenced this file since the project
// started and it has never existed, so `npm run deploy` has always failed.
//
// Deploying is not a thing to do casually here. A push is not a release, the
// Factory is authoring material rather than curriculum, and gated drafts must
// not reach a learner. So this refuses to run rather than trusting whoever typed
// the command to have checked.
//
// It also checks the commit author. Vercel blocks a deployment whose commit
// email it cannot match to a GitHub account on the team, and the failure is
// invisible from the CLI: the deployment sits at status UNKNOWN with no logs and
// no error, and the previous release keeps serving. Three deploys were lost to
// that before the dashboard said why. Catch it here, before the upload, where
// the message can say what to do.

import { execSync } from 'node:child_process';
import { existsSync, readFileSync } from 'node:fs';

const sh = cmd => execSync(cmd, { encoding: 'utf8' }).trim();
const die = (msg, fix) => {
  console.error(`\n  Refusing to deploy: ${msg}`);
  if (fix) console.error(`  ${fix}`);
  process.exit(1);
};

// 1. The working tree must be clean, so that what is deployed is what is on the
//    branch and can be found again later.
if (sh('git status --porcelain')) {
  die('the working tree has uncommitted changes.',
      'Commit or stash them, so the release matches a commit you can return to.');
}

// 2. The commit author must be a GitHub account Vercel can see.
const email = sh('git log -1 --format=%ae');
let account = null;
try {
  account = JSON.parse(sh('gh api user')).login;
} catch {
  die('cannot reach GitHub to check who the commit belongs to.', 'Run `gh auth login`.');
}
if (!email.includes(account)) {
  die(`the last commit is authored by ${email}, which is not ${account}.`,
      `Vercel will block this silently. Fix with:\n` +
      `    git config --global user.email "$(gh api user --jq '"\\(.id)+\\(.login)@users.noreply.github.com"')"\n` +
      `  then make a commit and try again.`);
}

// 3. The build must pass, and the bundle must not carry authoring material.
console.log('  building…');
sh('npm run build');

const bundle = sh('node -e "const fs=require(\'fs\');const d=\'dist/assets\';const f=fs.readdirSync(d).find(n=>/^index-.*\\.js$/.test(n));process.stdout.write(fs.readFileSync(d+\'/\'+f,\'utf8\'))"');
const mustNotShip = [
  ['a gated draft board', 'One Answer, Not Two'],
  ['a gated draft board', 'The Pattern in the Powers'],
  ['an authoring note', 'Founder direction'],
  ['a rejection reason', 'Not selected;'],
  ['the Factory chrome', 'authoring options']
];
const leaked = mustNotShip.filter(([, s]) => bundle.includes(s));
if (leaked.length) {
  die(`the bundle carries ${leaked.map(([w]) => w).join(', ')}.`,
      `Found: ${leaked.map(([, s]) => JSON.stringify(s)).join(', ')}\n` +
      '  Learner content is generated by scripts/build-pilot.mjs. Anything else\n' +
      '  reaching the bundle means something imported the Factory directly.');
}
console.log(`  bundle clean, ${(bundle.length / 1024).toFixed(0)} kB`);

// 4. Deploy.
if (!existsSync('.vercel/project.json')) die('this checkout is not linked to a Vercel project.', 'Run `vercel link`.');
const project = JSON.parse(readFileSync('.vercel/project.json', 'utf8')).projectName;
console.log(`  deploying ${project} to production…`);
console.log(execSync('vercel deploy --prod --yes --prebuilt=false', { encoding: 'utf8', stdio: 'pipe' }));
console.log('  done. Check that the production URL serves the new bundle before moving any domain.');
