// Production deploy to the dedicated Qubix University Vercel project.
// The Factory is authoring material rather than curriculum, and gated drafts
// must not reach a learner. This refuses to run unless the working tree, linked
// project and public bundle are all verified.

import { execSync, spawn } from 'node:child_process';
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

const PROJECT = 'qubix-university';
const DOMAIN = 'qubix.university';

// execSync returns null when stdio is inherited, so there is nothing to trim.
// Pinned rather than @latest. On 2026-08-27 vercel@latest could not install at
// all: it depends on @vercel/container@3.0.2, which is not published, so every
// deploy failed on npx before reaching Vercel. A deploy tool that breaks when
// somebody else publishes is not a deploy tool. Raise this deliberately.
const VERCEL = 'vercel@59.6.2';
const sh = (cmd, opts = {}) => (execSync(cmd, { encoding: 'utf8', ...opts }) || '').trim();
const die = (msg, fix) => {
  console.error(`\n  Refusing to deploy: ${msg}`);
  if (fix) console.error(`  ${fix}`);
  process.exit(1);
};

// 1. The working tree must be clean, so the release matches a commit.
if (sh('git status --porcelain')) {
  die('the working tree has uncommitted changes.',
      'Commit or stash them, so the release matches a commit you can return to.');
}
const sourceCommit = sh('git rev-parse --short HEAD');
const sourceBranch = sh('git rev-parse --abbrev-ref HEAD');

// 2. Refuse to deploy through an inherited or accidentally linked project. The
// Strata project once used this domain and must remain separate.
const projectFile = join('.vercel', 'project.json');
if (!existsSync(projectFile)) {
  die('this checkout is not linked to a Vercel project.',
      `Run "vercel link --project ${PROJECT}" and verify the account first.`);
}
const linkedProject = JSON.parse(readFileSync(projectFile, 'utf8'));
if (linkedProject.projectName !== PROJECT) {
  die(`this checkout is linked to ${linkedProject.projectName || 'an unknown project'}, not ${PROJECT}.`,
      'Relink the checkout to the dedicated Qubix University project.');
}

// 3. The commit author must match the owner of the configured private source
// remote. The remote and the release push are the authentication checks.
const sourceRemote = sh('git remote get-url origin');
const ownerMatch = sourceRemote.match(/github\.com[/:]([^/]+)\//i);
if (!ownerMatch) {
  die('the source remote is not a recognised GitHub repository.',
      `Configured origin: ${sourceRemote || '(none)'}`);
}
const account = ownerMatch[1];
const email = sh('git log -1 --format=%ae');
if (!email.includes(account)) {
  die(`the last commit is authored by ${email}, which is not ${account}.`,
      'Fix with:\n' +
      `    git config user.email "<id>+${account}@users.noreply.github.com"\n` +
      '  then make a commit and try again.');
}

// 4. Build.
console.log('  building…');
const packageRunner = process.env.npm_execpath
  ? `${JSON.stringify(process.execPath)} ${JSON.stringify(process.env.npm_execpath)} run build`
  : 'npm run build';
sh(packageRunner, { stdio: 'inherit' });

// 5. Nothing that belongs to authoring may reach a public deployment. The
// project source stays private, but browser bundles are public by definition.
const assets = join('dist', 'assets');
const js = readdirSync(assets).filter(n => n.endsWith('.js'))
  .map(n => readFileSync(join(assets, n), 'utf8')).join('\n');
const mustNotShip = [
  ['a gated draft board', 'One Answer, Not Two'],
  ['a gated draft board', 'The Pattern in the Powers'],
  ['a gated draft board', 'Where a Curve Turns'],
  ['an authoring note', 'Founder direction'],
  ['an authoring note', 'Rebuilt 2026'],
  ['a rejection reason', 'Not selected;'],
  ['the Factory chrome', 'authoring options']
];
const leaked = mustNotShip.filter(([, text]) => js.includes(text));
if (leaked.length) {
  die(`the bundle carries ${[...new Set(leaked.map(([what]) => what))].join(', ')}.`,
      `Found: ${leaked.map(([, text]) => JSON.stringify(text)).join(', ')}\n` +
      '  Learner content is generated by scripts/build-pilot.mjs. Anything else\n' +
      '  reaching the bundle means something imported the Factory directly.');
}
console.log(`  bundle clean, ${(js.length / 1024).toFixed(0)} kB of JavaScript checked`);

// 6. Open the thing in a browser before publishing it.
//
// Everything above reads files. Three defects in a row got past all of it and
// were found by a person opening the page: the front door would not scroll on a
// phone, a stage toggle updated its state and never re-rendered, and the whole
// floor threw on load and drew nothing. The bundle was correct in every case,
// which is why checking the bundle kept saying yes.
//
// So the last gate before a release is the page itself, served from the dist
// that is about to ship. Vercel's build image has no browser, which is why this
// lives here and not in prebuild.
//
// QUBIX_SKIP_RENDER_CHECK=1 exists for the day a browser will not start and a
// release genuinely cannot wait. Using it is a decision to publish something
// nobody has looked at.
if (process.env.QUBIX_SKIP_RENDER_CHECK === '1') {
  console.warn('\n  Skipping the rendered check. Nobody has opened this build.\n');
} else {
  console.log('  opening the build in a browser…');
  const preview = spawn(process.execPath, [join('node_modules', 'vite', 'bin', 'vite.js'),
    'preview', '--port', '4390', '--strictPort'], { stdio: 'ignore' });
  try {
    await new Promise(resolve => setTimeout(resolve, 6000));
    sh('node scripts/check-rendered.mjs http://localhost:4390', { stdio: 'inherit' });
  } catch (_) {
    die('the built site did not render correctly.',
      'Run "npx vite preview --port 4390" and "npm run check:rendered http://localhost:4390"\n'
      + '  to see which check failed. Nothing has been published.');
  } finally {
    preview.kill();
  }
}

// 7. Publish. Use the active package manager so the command works from npm and
// pnpm without requiring a globally installed Vercel CLI.
console.log('  publishing to Vercel…');
const execPath = JSON.stringify(process.execPath);
const packagePath = process.env.npm_execpath && JSON.stringify(process.env.npm_execpath);
// Single quotes here meant ${VERCEL} was never interpolated, so the npm branch
// ran `npx --yes` with no package name and the pin was silently lost. Only the
// pnpm branch was ever exercised, which is why it survived.
const vercel = packagePath && /pnpm/i.test(process.env.npm_execpath)
  ? `${execPath} ${packagePath} dlx ${VERCEL}`
  : `npx --yes ${VERCEL}`;
sh(`${vercel} deploy --prod --yes`, { stdio: 'inherit' });

console.log(`  deployed ${sourceCommit} from ${sourceBranch}.`);
console.log(`  verify https://${DOMAIN}/ and its response security headers.`);
